version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpostgres
      POSTGRES_DB: myappdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  sqlstudio:
    image: frectonz/sql-studio
    restart: always
    ports:
      - "3030:3030"
    command:
      - /bin/sql-studio
      - --no-browser
      - --no-shutdown
      - --address=0.0.0.0:3030
      - postgres
      - postgres://postgres:localpostgres@db:5432/myappdb
    depends_on:
      - db

volumes:
  dbdata: